version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  flaskapp:
    build: .
    container_name: flaskapp
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://username:password@mongodb:27017"

volumes:
  mongodb_data:
